In [4]:
import numpy as np
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

    
training_inputs = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])

training_outputs = np.array([[0,1,1,0]]).T

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3,1)) - 1

print('Random starting synaptic weights')
print(synaptic_weights)

for iteration in range(110000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - outputs
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights = synaptic_weights + np.dot(input_layer.T, adjustments)

print("Synaptic Weights after training :")    
print(synaptic_weights)

print("Outputs After training :")
print(outputs)
    

Random starting synaptic weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic Weights after training :
[[12.10471586]
 [-0.2043345 ]
 [-5.8483515 ]]
Outputs After training :
[[0.00287637]
 [0.99765243]
 [0.99808546]
 [0.00234603]]
